GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "Putri Namira"
}

###

PATCH http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "todo": "Aldi Nug"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id" : 0
}